apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kubecafe-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
  - hosts:
      - kubecafe.local
    secretName: kubecafe-tls
  rules:
  - host: kubecafe.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 3000
