name: Build and Deploy

on:
  push:
    branches: [ main, develop ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build & Push Backend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/kubecafe-backend ./backend
          docker push ${{ secrets.DOCKER_USERNAME }}/kubecafe-backend

      - name: Build & Push Frontend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/kubecafe-frontend ./frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/kubecafe-frontend

      - name: Deploy to Cluster
        run: |
          kubectl apply -f k8s/
